# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
